[2023-06-14T21:30:04.919+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:24:54.781024+00:00 [queued]>
[2023-06-14T21:30:04.926+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:24:54.781024+00:00 [queued]>
[2023-06-14T21:30:04.929+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2023-06-14T21:30:04.943+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2023-06-14 21:24:54.781024+00:00
[2023-06-14T21:30:04.949+0000] {standard_task_runner.py:57} INFO - Started process 443 to run task
[2023-06-14T21:30:04.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2023-06-14T21:24:54.781024+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp0k3htlf6']
[2023-06-14T21:30:04.968+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask pyspark_train_classifier_model
[2023-06-14T21:30:05.034+0000] {task_command.py:410} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-14T21:24:54.781024+00:00 [running]> on host 6426fae5ea9e
[2023-06-14T21:30:05.134+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='agile_data_science_batch_prediction_model_training' AIRFLOW_CTX_TASK_ID='pyspark_train_classifier_model' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T21:24:54.781024+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T21:24:54.781024+00:00'
[2023-06-14T21:30:05.136+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-14T21:30:05.137+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\nspark-submit --master spark://spark-master:7077   //resources/train_spark_mllib_model.py   /']
[2023-06-14T21:30:05.151+0000] {subprocess.py:86} INFO - Output:
[2023-06-14T21:30:05.157+0000] {subprocess.py:93} INFO - /bin/bash: line 2: spark-submit: command not found
[2023-06-14T21:30:05.158+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-14T21:30:05.181+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-14T21:30:05.187+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20230614T212454, start_date=20230614T213004, end_date=20230614T213005
[2023-06-14T21:30:05.197+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 22 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 127.; 443)
[2023-06-14T21:30:05.212+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-14T21:30:05.230+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
