[2023-06-12T18:19:13.577+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-12T16:02:08.941541+00:00 [queued]>
[2023-06-12T18:19:13.583+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-12T16:02:08.941541+00:00 [queued]>
[2023-06-12T18:19:13.584+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-06-12T18:19:13.593+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2023-06-12 16:02:08.941541+00:00
[2023-06-12T18:19:13.598+0000] {standard_task_runner.py:57} INFO - Started process 763 to run task
[2023-06-12T18:19:13.603+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2023-06-12T16:02:08.941541+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpa3vpv_9r']
[2023-06-12T18:19:13.606+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask pyspark_train_classifier_model
[2023-06-12T18:19:13.665+0000] {task_command.py:410} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2023-06-12T16:02:08.941541+00:00 [running]> on host 937cd7c7e052
[2023-06-12T18:19:13.747+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='agile_data_science_batch_prediction_model_training' AIRFLOW_CTX_TASK_ID='pyspark_train_classifier_model' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T16:02:08.941541+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-12T16:02:08.941541+00:00'
[2023-06-12T18:19:13.749+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-12T18:19:13.750+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\ndocker-compose -f docker-compose.train.yml -e "CSV_FILE=carrefour_data_v1.csv"']
[2023-06-12T18:19:13.765+0000] {subprocess.py:86} INFO - Output:
[2023-06-12T18:19:13.769+0000] {subprocess.py:93} INFO - /bin/bash: line 2: docker-compose: command not found
[2023-06-12T18:19:13.769+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-06-12T18:19:13.785+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-06-12T18:19:13.788+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20230612T160208, start_date=20230612T181913, end_date=20230612T181913
[2023-06-12T18:19:13.799+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 127.; 763)
[2023-06-12T18:19:13.816+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-12T18:19:13.836+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
